source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.1.0'
gem 'devise', '3.4.1'
gem 'figaro'
gem 'font-awesome-rails'
gem 'geo_ip'
gem 'geocoder'
gem 'gon'
gem 'google-webfonts-rails'
gem 'htmlbeautifier'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
gem 'mustachejs-rails'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-linkedin'
gem 'omniauth-twitter'
gem 'pry-rails'
gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'simple_form'
gem 'turbolinks'
gem 'twitter-bootstrap-rails', git: 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'rubocop'
  gem 'shoulda-matchers'
  gem 'spring'
  gem 'sqlite3'
  gem 'web-console', '~> 2.0'
end

group :production do
  gem 'pg'
  gem 'rails_12factor'
end
