# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98f5e96b629a10f3101c171e56302c1a6276e1d1cbbc35bd78bd39dbafe67969f8459d3f5eedc8111229902c3e459a9e9cef0b640a5ef27ad4ff65a9d79d054b
  WEATHER_API_KEY: 66922ca7ee25d20d
  IP_INFO_API_KEY: 9ec04c68eba7c73852078ec8db83aea4b4a44537b05181023546ed701667f5af
  GOOGLE_MAPS_API_KEY: AIzaSyD-7NSPt2Gzjn79uQ-NoKl7xGKc0oO4H54
  FACEBOOK_API_KEY:  952135701508696 
  FACEBOOK_API_SECRET: c8023d0c1ff4c876ee7959b2420f85dd
  GOOGLE_API_KEY:  645573209535-on03jvng731shtk814jdof5mp269btsr.apps.googleusercontent.com
  GOOGLE_API_SECRET: I6yBWWDiAwoYErX0zho3GoS7
  LINKEDIN_API_KEY: 77e39s7qucn8p4
  LINKEDIN_API_SECRET: HO0P0HXaTK2MZlYR
  GITHB_API_KEY: 175ab9574c9c7d27e9b0
  GITHB_API_SECRET: 984ed777f7b1d90f935b1879d3e8b05f53286b70

test:
  secret_key_base: 93b911d5e93ff5f48a85f45d076b4b53ca7b5bf5f32b7a074ed3b5d128360adfa5f806d91439a9e9e4187f9f8fb5c751d021c80f4708187c1fc5f6848edf5b46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  weather_api_key: 66922ca7ee25d20d
  ip_info_api_key: 9ec04c68eba7c73852078ec8db83aea4b4a44537b05181023546ed701667f5af
  google_maps_api_key: AIzaSyD-7NSPt2Gzjn79uQ-NoKl7xGKc0oO4H54
  facebook_api_key: <%= ENV["FACEBOOK_API_KEY"] %>
  facebook_api_secret: <%= ENV["FACEBOOK_API_SECRET"] %>
  google_api_key:   <%= ENV["GOOGLE_API_KEY"] %>
  google_api_secret:  <%= ENV["GOOGLE_API_SECRET"] %>
  linkedin_api_key:  <%= ENV["LINKEDIN_API_KEY"] %>
  linkedin_api_secret:  <%= ENV["LINKEDIN_API_SECRET"] %>
  github_api_key:  <%= ENV["GITHB_API_KEY"] %>
  github_api_secret:  <%= ENV["GITHB_API_SECRET"] %>

