
	DefaultItem.create(item: 'Toothpaste', category: 'Toiletries')
	DefaultItem.create(item: 'Dental Floss', category: 'Toiletries')
	DefaultItem.create(item: 'Soap', category: 'Toiletries')
	DefaultItem.create(item: 'Shampoo', category: 'Toiletries')
	DefaultItem.create(item: 'Brush', category: 'Toiletries')
	DefaultItem.create(item: 'Hairstyling Essentials', category: 'Toiletries')
	DefaultItem.create(item: 'Face Cleanser', category: 'Toiletries')
	DefaultItem.create(item: 'Face Lotion', category: 'Toiletries')
	DefaultItem.create(item: 'Sunscreen', category: 'Toiletries')
	DefaultItem.create(item: 'Moisturizer', category: 'Toiletries')
	DefaultItem.create(item: 'Shaving Supplies', category: 'Toiletries')
	DefaultItem.create(item: 'Makeup', category: 'Toiletries')	
	DefaultItem.create(item: 'Makeup Remover', category: 'Toiletries')
	DefaultItem.create(item: 'Hygeine Products', category: 'Toiletries')
	DefaultItem.create(item: 'Nail file / Clippers', category: 'Toiletries')	
	DefaultItem.create(item: 'Tweezers', category: 'Toiletries')	
	DefaultItem.create(item: 'Hand Sanitizer', category: 'Toiletries')	
	DefaultItem.create(item: 'Bandages', category: 'Toiletries')	
	DefaultItem.create(item: 'First Aid Kit', category: 'Toiletries')	
	DefaultItem.create(item: 'Insect Repellant', category: 'Toiletries')	
	DefaultItem.create(item: 'Medications', category: 'Toiletries')	
	DefaultItem.create(item: 'Pain Relievers', category: 'Toiletries')	
	DefaultItem.create(item: 'Vitamins', category: 'Toiletries')		
	DefaultItem.create(item: 'Laundry Kit', category: 'Clothes')	
	DefaultItem.create(item: 'Laundry Bag', category: 'Clothes')	
	DefaultItem.create(item: 'Leisure Shoes', category: 'Clothes')	
	DefaultItem.create(item: 'Underwear', category: 'Clothes')	
	DefaultItem.create(item: 'Socks', category: 'Clothes')	
	DefaultItem.create(item: 'Sleepwear', category: 'Clothes')	
	DefaultItem.create(item: 'T-Shirts', category: 'Clothes')	
	DefaultItem.create(item: 'Dress Shirts', category: 'Clothes')	
	DefaultItem.create(item: 'Casual Shirts', category: 'Clothes')	
	DefaultItem.create(item: 'Jeans', category: 'Clothes')	
	DefaultItem.create(item: 'Pants', category: 'Clothes')	
	DefaultItem.create(item: 'Shorts', category: 'Clothes')	
	DefaultItem.create(item: 'Dresses', category: 'Clothes')	
	DefaultItem.create(item: 'Skirts', category: 'Clothes')		
	DefaultItem.create(item: 'Sweaters', category: 'Clothes')		
	DefaultItem.create(item: 'Coats / Jackets', category: 'Clothes')		
	DefaultItem.create(item: 'Hats', category: 'Clothes')		
	DefaultItem.create(item: 'Gloves', category: 'Clothes')		
	DefaultItem.create(item: 'Scarves', category: 'Clothes')		
	DefaultItem.create(item: 'Umbrella', category: 'Clothes')		
	DefaultItem.create(item: 'Athletic Shoes', category: 'Clothes')		
	DefaultItem.create(item: 'Rain Boots', category: 'Clothes')		
	DefaultItem.create(item: 'Dress Shoes', category: 'Clothes')		
	DefaultItem.create(item: 'Sandals / Flip-Flops', category: 'Clothes')		
	DefaultItem.create(item: 'Belts', category: 'Clothes')	
	DefaultItem.create(item: 'Ties', category: 'Clothes')	
	DefaultItem.create(item: 'Jewelry', category: 'Clothes')	
	DefaultItem.create(item: 'Purses', category: 'Clothes')	
	DefaultItem.create(item: 'Collapsible Totes', category: 'Clothes')	
	DefaultItem.create(item: 'Plane Tickets', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Hotel Confirmation', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Rental Car Confirmation', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Cash / Credit Cards', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Dollar Bills for Tips', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Checkbook', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Passports', category: 'Travel Paperwork')				
	DefaultItem.create(item: 'Birth Certificates', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'ID / Drivers License', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Health Insurance Card', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Maps / Directions', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Membership Cards', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Address Book', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Notepad / Pens', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Batteries', category: 'Electronics')	
	DefaultItem.create(item: 'Cameras / Chargers', category: 'Electronics')
	DefaultItem.create(item: 'Camera Lenses', category: 'Electronics')
	DefaultItem.create(item: 'Camera Tripod', category: 'Electronics')
	DefaultItem.create(item: 'Cellphones / Chargers', category: 'Electronics')
	DefaultItem.create(item: 'MP3 Player', category: 'Electronics')
	DefaultItem.create(item: 'Laptops / Chargers', category: 'Electronics')
	DefaultItem.create(item: 'Headphones', category: 'Electronics')
	DefaultItem.create(item: 'Multipower Outlet', category: 'Electronics')
	DefaultItem.create(item: 'Voltage Adaptor', category: 'Electronics')
	DefaultItem.create(item: 'Hair Dryer', category: 'Electronics')
	DefaultItem.create(item: 'Watch', category: 'Electronics')	
	DefaultItem.create(item: 'Alarm Clock', category: 'Electronics')	
	DefaultItem.create(item: 'GPS', category: 'Electronics')		
	DefaultItem.create(item: 'Books', category: 'Carry-on')	
	DefaultItem.create(item: 'Tissues', category: 'Carry-on')	
	DefaultItem.create(item: 'Travel Pillow', category: 'Carry-on')	
	DefaultItem.create(item: 'Lip Balm', category: 'Carry-on')	
	DefaultItem.create(item: 'Change of Clothes', category: 'Carry-on')	
	DefaultItem.create(item: 'Empty Water Bottle', category: 'Carry-on')	
	DefaultItem.create(item: 'In-flight Medications', category: 'Carry-on')	
	DefaultItem.create(item: 'Valuables', category: 'Carry-on')	
	DefaultItem.create(item: 'Sleeping Mask', category: 'Carry-on')	
	DefaultItem.create(item: 'Multi-tool', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Bottle Opener', category: 'Miscellaneous')		
	DefaultItem.create(item: 'Cork Screw', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Poker Cards', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Lighter', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Flash Light', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Sunglasses', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Safety Pins', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Duct Tape', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Super Glue', category: 'Miscellaneous')	


ActivityItem.create(item_name: "Down jacket", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Waterproof jacket", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Waterproof trousers and gaiters", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Breathable wicking layers", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Thermal underwear", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Walking socks", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Walking boots", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Warm hat", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Gloves or mittens", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Trekking Kit", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Waterproof rucksack cover", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Map and compass", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Walking poles", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Water bottles or hydration system", activity_name: "Trekking-Winter-Polar")
ActivityItem.create(item_name: "Leave at base bag", activity_name: "Trekking-Winter-Polar")

ActivityItem.create(item_name: "Long Underwear", activity_name: "Camping")
ActivityItem.create(item_name: "Utility knife", activity_name: "Camping")
ActivityItem.create(item_name: "Towel", activity_name: "Camping")
ActivityItem.create(item_name: "Handheld GPS", activity_name: "Camping")
ActivityItem.create(item_name: "Compass", activity_name: "Camping")
ActivityItem.create(item_name: "Water Filter", activity_name: "Camping")
ActivityItem.create(item_name: "First aid Kit", activity_name: "Camping")
ActivityItem.create(item_name: "Bug Spray/Insect Repeller", activity_name: "Camping")
ActivityItem.create(item_name: "Tick Remover", activity_name: "Camping")
ActivityItem.create(item_name: "Snacks", activity_name: "Camping")
ActivityItem.create(item_name: "Camping food", activity_name: "Camping")
ActivityItem.create(item_name: "Matches/Lighter/Fire starter", activity_name: "Camping")
ActivityItem.create(item_name: "Firewood", activity_name: "Camping")
ActivityItem.create(item_name: "Headlamp", activity_name: "Camping")
ActivityItem.create(item_name: "Flashlight", activity_name: "Camping")
ActivityItem.create(item_name: "Cooking Tools", activity_name: "Camping")
ActivityItem.create(item_name: "Eating Utensils", activity_name: "Camping")
ActivityItem.create(item_name: "Pillow", activity_name: "Camping")
ActivityItem.create(item_name: "Sleeping Pad", activity_name: "Camping")
ActivityItem.create(item_name: "Tent", activity_name: "Camping")
ActivityItem.create(item_name: "Air Mattress", activity_name: "Camping")
ActivityItem.create(item_name: "Fishing gear", activity_name: "Camping")

ActivityItem.create(item_name: "Handheld GPS", activity_name: "Hiking")
ActivityItem.create(item_name: "Compass", activity_name: "Hiking")
ActivityItem.create(item_name: "First Aid Kit", activity_name: "Hiking")
ActivityItem.create(item_name: "Bug Spray", activity_name: "Hiking")
ActivityItem.create(item_name: "Hiking Shoes", activity_name: "Hiking")


ActivityItem.create(item_name: "Water shoes", activity_name: "Beach-Summer-Swimming")
ActivityItem.create(item_name: "Floating Tube", activity_name: "Beach-Summer-Swimming")
ActivityItem.create(item_name: "Swimsuit", activity_name: "Beach-Summer-Swimming")
ActivityItem.create(item_name: "Beach towel", activity_name: "Beach-Summer-Swimming")
ActivityItem.create(item_name: "Swim Cover-ups", activity_name: "Beach-Summer-Swimming")
ActivityItem.create(item_name: "Sandals", activity_name: "Beach-Summer-Swimming")
ActivityItem.create(item_name: "Hat", activity_name: "Beach-Summer-Swimming")
ActivityItem.create(item_name: "Sunscreen", activity_name: "Beach-Summer-Swimming")
ActivityItem.create(item_name: "Sunglasses", activity_name: "Beach-Summer-Swimming")


ActivityItem.create(item_name: "Bicycle Light", activity_name: "Bicycling")
ActivityItem.create(item_name: "Bicycle Shirt", activity_name: "Bicycling")
ActivityItem.create(item_name: "Bicycle Shorts", activity_name: "Bicycling")
ActivityItem.create(item_name: "Sunglasses", activity_name: "Bicycling")
ActivityItem.create(item_name: "Helmet", activity_name: "Bicycling")
ActivityItem.create(item_name: "Bicycle Shoes", activity_name: "Bicycling")

ActivityItem.create(item_name: "Camera Bag", activity_name: "Photography")
ActivityItem.create(item_name: "Battery Charger", activity_name: "Photography")
ActivityItem.create(item_name: "Camera Charger", activity_name: "Photography")
ActivityItem.create(item_name: "Memory Cards", activity_name: "Photography")
ActivityItem.create(item_name: "Monopod", activity_name: "Photography")
ActivityItem.create(item_name: "Tripod", activity_name: "Photography")
ActivityItem.create(item_name: "Camera", activity_name: "Photography")
ActivityItem.create(item_name: "Lenses", activity_name: "Photography")

ActivityItem.create(item_name: "Business Cards", activity_name: "Working")
ActivityItem.create(item_name: "Work Cell Phone", activity_name: "Working")
ActivityItem.create(item_name: "Work Cell Phone Charger", activity_name: "Working")
ActivityItem.create(item_name: "Work Badge", activity_name: "Working")
ActivityItem.create(item_name: "Laptop", activity_name: "Working")
ActivityItem.create(item_name: "Laptop Charger", activity_name: "Working")
ActivityItem.create(item_name: "Portable Wifi", activity_name: "Working")
ActivityItem.create(item_name: "Business Contacts", activity_name: "Working")

ActivityItem.create(item_name: "Running Headphones", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Music Player", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Running Shirt", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Running Shorts", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Running Shoes", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Runnning Socks", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Activity Tracker (ex. Fitbit)", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Water Bottle", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Padlock", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Gym Towel", activity_name: "Running-Gym")
ActivityItem.create(item_name: "Sports Bra", activity_name: "Running-Gym")

ActivityItem.create(item_name: "Baby Sunscreen", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Consent To Travel Form", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Gas Reliever", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Birth Certificate", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Collapsible Stroller", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Car Seat", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Inflatable Baby Bathtub", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Portable Crib / Play Yard", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Sling / Front Carrier", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Pain Reliever", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "First Aid Kit", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Breastpump", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Energy Snacks", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Sippy Cup", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Bottle / Nipples", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Water / Juice", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Formula", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Food", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Hat", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Clothes/Shoes/Socks", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Bsby Toys", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Pacifier", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Tissues", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Lotion", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Soap", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Hand Sanitizer", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Baby Wipes", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Diaper Rash Cream", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "PLastic Bags", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Blankets", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Changing Pad", activity_name: "Baby-On-Board")
ActivityItem.create(item_name: "Diapers", activity_name: "Baby-On-Board")




