
	DefaultItem.create(item: 'Toothpaste', category: 'Toiletries')
	DefaultItem.create(item: 'Dental Floss', category: 'Toiletries')
	DefaultItem.create(item: 'Soap', category: 'Toiletries')
	DefaultItem.create(item: 'Shampoo', category: 'Toiletries')
	DefaultItem.create(item: 'Brush', category: 'Toiletries')
	DefaultItem.create(item: 'Hairstyling Essentials', category: 'Toiletries')
	DefaultItem.create(item: 'Face Cleanser', category: 'Toiletries')
	DefaultItem.create(item: 'Face Lotion', category: 'Toiletries')
	DefaultItem.create(item: 'Sunscreen', category: 'Toiletries')
	DefaultItem.create(item: 'Moisturizer', category: 'Toiletries')
	DefaultItem.create(item: 'Shaving Supplies', category: 'Toiletries')
	DefaultItem.create(item: 'Makeup', category: 'Toiletries')	
	DefaultItem.create(item: 'Makeup Remover', category: 'Toiletries')
	DefaultItem.create(item: 'Hygeine Products', category: 'Toiletries')
	DefaultItem.create(item: 'Nail file / Clippers', category: 'Toiletries')	
	DefaultItem.create(item: 'Tweezers', category: 'Toiletries')	
	DefaultItem.create(item: 'Hand Sanitizer', category: 'Toiletries')	
	DefaultItem.create(item: 'Bandages', category: 'Toiletries')	
	DefaultItem.create(item: 'First Aid Kit', category: 'Toiletries')	
	DefaultItem.create(item: 'Insect Repellant', category: 'Toiletries')	
	DefaultItem.create(item: 'Medications', category: 'Toiletries')	
	DefaultItem.create(item: 'Pain Relievers', category: 'Toiletries')	
	DefaultItem.create(item: 'Vitamins', category: 'Toiletries')		
	DefaultItem.create(item: 'Laundry Kit', category: 'Clothes')	
	DefaultItem.create(item: 'Laundry Bag', category: 'Clothes')	
	DefaultItem.create(item: 'Leisure Shoes', category: 'Clothes')	
	DefaultItem.create(item: 'Underwear', category: 'Clothes')	
	DefaultItem.create(item: 'Socks', category: 'Clothes')	
	DefaultItem.create(item: 'Sleepwear', category: 'Clothes')	
	DefaultItem.create(item: 'T-Shirts', category: 'Clothes')	
	DefaultItem.create(item: 'Dress Shirts', category: 'Clothes')	
	DefaultItem.create(item: 'Casual Shirts', category: 'Clothes')	
	DefaultItem.create(item: 'Jeans', category: 'Clothes')	
	DefaultItem.create(item: 'Pants', category: 'Clothes')	
	DefaultItem.create(item: 'Shorts', category: 'Clothes')	
	DefaultItem.create(item: 'Dresses', category: 'Clothes')	
	DefaultItem.create(item: 'Skirts', category: 'Clothes')		
	DefaultItem.create(item: 'Sweaters', category: 'Clothes')		
	DefaultItem.create(item: 'Coats / Jackets', category: 'Clothes')		
	DefaultItem.create(item: 'Hats', category: 'Clothes')		
	DefaultItem.create(item: 'Gloves', category: 'Clothes')		
	DefaultItem.create(item: 'Scarves', category: 'Clothes')		
	DefaultItem.create(item: 'Umbrella', category: 'Clothes')		
	DefaultItem.create(item: 'Athletic Shoes', category: 'Clothes')		
	DefaultItem.create(item: 'Rain Boots', category: 'Clothes')		
	DefaultItem.create(item: 'Dress Shoes', category: 'Clothes')		
	DefaultItem.create(item: 'Sandals / Flip-Flops', category: 'Clothes')		
	DefaultItem.create(item: 'Belts', category: 'Clothes')	
	DefaultItem.create(item: 'Ties', category: 'Clothes')	
	DefaultItem.create(item: 'Jewelry', category: 'Clothes')	
	DefaultItem.create(item: 'Purses', category: 'Clothes')	
	DefaultItem.create(item: 'Collapsible Totes', category: 'Clothes')	
	DefaultItem.create(item: 'Plane Tickets', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Hotel Confirmation', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Rental Car Confirmation', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Cash / Credit Cards', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Dollar Bills for Tips', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Checkbook', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Passports', category: 'Travel Paperwork')				
	DefaultItem.create(item: 'Birth Certificates', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'ID / Drivers License', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Health Insurance Card', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Maps / Directions', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Membership Cards', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Address Book', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Notepad / Pens', category: 'Travel Paperwork')	
	DefaultItem.create(item: 'Batteries', category: 'Electronics')	
	DefaultItem.create(item: 'Cameras / Chargers', category: 'Electronics')
	DefaultItem.create(item: 'Camera Lenses', category: 'Electronics')
	DefaultItem.create(item: 'Camera Tripod', category: 'Electronics')
	DefaultItem.create(item: 'Cellphones / Chargers', category: 'Electronics')
	DefaultItem.create(item: 'MP3 Player', category: 'Electronics')
	DefaultItem.create(item: 'Laptops / Chargers', category: 'Electronics')
	DefaultItem.create(item: 'Headphones', category: 'Electronics')
	DefaultItem.create(item: 'Multipower Outlet', category: 'Electronics')
	DefaultItem.create(item: 'Voltage Adaptor', category: 'Electronics')
	DefaultItem.create(item: 'Hair Dryer', category: 'Electronics')
	DefaultItem.create(item: 'Watch', category: 'Electronics')	
	DefaultItem.create(item: 'Alarm Clock', category: 'Electronics')	
	DefaultItem.create(item: 'GPS', category: 'Electronics')		
	DefaultItem.create(item: 'Books', category: 'Carry-on')	
	DefaultItem.create(item: 'Tissues', category: 'Carry-on')	
	DefaultItem.create(item: 'Travel Pillow', category: 'Carry-on')	
	DefaultItem.create(item: 'Lip Balm', category: 'Carry-on')	
	DefaultItem.create(item: 'Change of Clothes', category: 'Carry-on')	
	DefaultItem.create(item: 'Empty Water Bottle', category: 'Carry-on')	
	DefaultItem.create(item: 'In-flight Medications', category: 'Carry-on')	
	DefaultItem.create(item: 'Valuables', category: 'Carry-on')	
	DefaultItem.create(item: 'Sleeping Mask', category: 'Carry-on')	
	DefaultItem.create(item: 'Multi-tool', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Bottle Opener', category: 'Miscellaneous')		
	DefaultItem.create(item: 'Cork Screw', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Poker Cards', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Lighter', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Flash Light', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Sunglasses', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Safety Pins', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Duct Tape', category: 'Miscellaneous')	
	DefaultItem.create(item: 'Super Glue', category: 'Miscellaneous')	


	ActivityItem.create(activity_name: 'Bicycling')
	ActivityItem.create(activity_name: 'Hiking')
	ActivityItem.create(activity_name: 'Running-Gym')
	ActivityItem.create(activity_name: 'Baby-On-Board')
	ActivityItem.create(activity_name: 'Camping')
	ActivityItem.create(activity_name: 'Working')
	ActivityItem.create(activity_name: 'Photography')
	ActivityItem.create(activity_name: 'Beach-Summer-Swimming')
	ActivityItem.create(activity_name: 'Trekking-Winter-Polar')
